export const SSI_UNLOCKED_DOC_VIEWER_TEST_ID = 'SSI_UNLOCKED_DOC_VIEWER_TEST_ID'
export const DOWNLOAD_SSI_TEST_ID = 'DOWNLOAD_SSI_TEST_ID'
export const MORE_OPTIONS_TEST_ID = 'MORE_OPTIONS_TEST_ID'
export const TOGGLE_ANSWERS_TEST_ID = 'TOGGLE_ANSWERS_TEST_ID'
export const QUESTION_PANEL_CONTAINER_TEST_ID = 'QUESTION_PANEL_CONTAINER_TEST_ID'
export const NAVIGATION_TEST_ID = 'NAVIGATION_TEST_ID'
export const NAVIGATION_INPUT_TEST_ID = 'NAVIGATION_INPUT_TEST_ID'
export const NAVIGATION_PAGE_TOTAL_TEST_ID = 'NAVIGATION_PAGE_TOTAL_TEST_ID'
export const TEST_DB_FILENAME = 9449927
export const DBFILENAME_17_PAGE_LENGTH = 4
export const SSI_ROTATE_TEST_ID = 'SSI_ROTATE_TEST_ID'
export const SSI_ROTATE_TEST_ID_RIGHT = 'SSI_ROTATE_TEST_ID_RIGHT'
export const SSI_ROTATE_TEST_ID_LEFT = 'SSI_ROTATE_TEST_ID_LEFT'
export const SSI_VIEWPORT_ROTATION_TEST_ID = 'SSI_VIEWPORT_ROTATION_TEST_ID'
export const SSI_PRINT_TEST_ID = 'SSI_PRINT_TEST_ID'
export const SSI_FULL_SCREEN_TEST_ID = 'SSI_FULL_SCREEN_TEST_ID'
export const SSI_ZOOM_TEST_ID = 'SSI_ZOOM_TEST_ID'
export const SSI_SEARCH_TEST_ID = 'SSI_SEARCH_TEST_ID'
export const SSI_SEARCH_INPUT_TEST_ID = 'SSI_SEARCH_INPUT_TEST_ID'
export const SSI_SEARCH_INPUT_CLEAR_TEST_ID = 'SSI_SEARCH_INPUT_CLEAR_TEST_ID'
export const SSI_SEARCH_INPUT_INCREMENT_TEST_ID = 'SSI_SEARCH_INPUT_INCREMENT_TEST_ID'
export const SSI_SEARCH_INPUT_DECREMENT_TEST_ID = 'SSI_SEARCH_INPUT_DECREMENT_TEST_ID'
export const SSI_SIDEBAR_TOGGLE_TEST_ID = 'SSI_SIDEBAR_TOGGLE_TEST_ID'
export const SSI_ZOOM_OUT_TEST_ID = 'SSI_ZOOM_OUT_TEST_ID'
export const SSI_ZOOM_IN_TEST_ID = 'SSI_ZOOM_IN_TEST_ID'
export const SSI_ZOOM_SELECTOR_TEST_ID = 'SSI_ZOOM_SELECTOR_TEST_ID'
export const SSI_SEARCH_RESULT_TOTAL_TEST_ID = 'SSI_SEARCH_RESULT_TOTAL_TEST_ID'
export const SSI_THUMBNAIL_TEST_ID = 'SSI_THUMBNAIL_TEST_ID'

/**
 * ATD constants
 */
export const SSI_INFO_CONTAINER_TEST_ID = 'SSI_INFO_CONTAINER'
export const SSI_ATD_QUESTION_FORM_TEST_ID = 'SSI_ATD_QUESTION_FORM'
export const SSI_ATD_CROPBOX_TEST_ID = 'SSI_ATD_CROPBOX_TEST_ID'
export const SSI_ATD_CONTAINER_TEST_ID = 'SSI_ATD_CONTAINER_TEST_ID'
export const SSI_ATD_ANSWER_CONTAINER_TEST_ID = 'ATD_CONTAINER_TEST_ID'

export const ATD_SIDEBAR_CONTAINER_TEST_ID = 'atd-sidebar-container'
export const ATD_NAVIGATION_CONTAINER_TEST_ID = 'atd-navigation-container'

/**
 * CAAP
 */
export const SSI_UNLOCKED_DOC_HEADER_TEST_ID = 'SSI_UNLOCKED_DOC_HEADER_TEST_ID'
export const SSI_UNLOCKED_SIDEBAR_TEST_ID = 'SSI_UNLOCKED_SIDEBAR_TEST_ID'

/**
 * CHAT
 */
export const MESSAGE_TEXT_BUBBLE_ID = 'MESSAGE_TEXT_BUBBLE_ID'

export enum RotateOption {
    NONE,
    ROTATE_90,
    ROTATE_180,
    ROTATE_270,
}

export enum FullscreenStatus {
    OFF,
    START,
    ON,
    END,
    ERROR,
}

export enum ZoomOption {
    FIT_TO_WIDTH,
    PERCENT_10,
    PERCENT_25,
    PERCENT_50,
    PERCENT_75,
    PERCENT_100,
    PERCENT_150,
    PERCENT_200,
    CUSTOM, 
}

export enum PointerDirection {
    UP = 'up',
    DOWN = 'down',
}